# -------------------------------------------------------------------------------------
# Media Types
# See: https://gohugo.io/templates/output-formats/#media-types
# -------------------------------------------------------------------------------------

  # [mediaTypes."application/feed+json"]
  #   suffixes = ["json"]
